name: morpheme_cli
description: "Morpheme CLI Boost productivity with modular project creation, API generation & folder structuring tools. Simplify Flutter dev! #Flutter #CLI"
version: 3.4.1
homepage: https://morpheme.design/
repository: https://github.com/morphemedesign/morpheme-flutter-cli

environment:
  sdk: "^3.6.0"

dependencies:
  args: ^2.6.0
  path: ^1.9.1
  yaml: ^3.1.3
  collection: ^1.19.1
  path_to_regexp: ^0.4.0
  yaml_writer: ^2.0.1
  equatable: ^2.0.7
  archive: ^4.0.2
  intl: ^0.20.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14

executables:
  morpheme: morpheme
